name: 'Local Runner Cache'
description: 'Cache files and folders locally on the runner filesystem for faster builds'
author: 'Ozan Kaşıkçı'
branding:
  icon: 'archive'
  color: 'blue'

inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache'
    required: true
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring stale cache if no cache hit occurred for key'
    required: false
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms'
    default: 'false'
    required: false
  cache-dir:
    description: 'Directory where cache files will be stored. Defaults to ~/.cache/github-actions-local-cache'
    required: false
  lock-timeout:
    description: 'Maximum time in seconds to wait for file locks before breaking them. Defaults to 60 seconds'
    default: '60'
    required: false

outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
  cache-primary-key:
    description: 'The key used to store the cache'
  cache-matched-key:
    description: 'The key of the cache that was restored (if any)'

runs:
  using: 'node20'
  main: 'dist/main.js'
  post: 'dist/post.js'