name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Build and package
      run: npm run all

    - name: Check if release exists
      id: check_release
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        if gh release view "$TAG_NAME" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Release $TAG_NAME already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Release $TAG_NAME does not exist"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      if: steps.check_release.outputs.exists == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Updated dependencies
          - Bug fixes and improvements
        draft: false
        prerelease: false

    - name: Release already exists
      if: steps.check_release.outputs.exists == 'true'
      run: |
        echo "Release already exists. Skipping release creation."
        echo "You can view the existing release at: https://github.com/${{ github.repository }}/releases/tag/${GITHUB_REF#refs/tags/}"