name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run linting
      run: npm run lint
    
    - name: Build
      run: npm run build
    
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create release branch with built files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Create release branch
        git checkout -b release/${{ steps.version.outputs.VERSION }}
        
        # Add built files (temporarily override .gitignore)
        git add -f dist/main.js dist/post.js
        git commit -m "Add built files for ${{ steps.version.outputs.VERSION }}"
        git push origin release/${{ steps.version.outputs.VERSION }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ## 🚀 What's New in ${{ steps.version.outputs.VERSION }}
          
          ### 🔐 **Integrity Verification System**
          - SHA-256 checksum generation and verification  
          - Automatic corruption detection and cleanup
          - Dual verification (checksum + tar structure)
          
          ### 🔒 **Concurrency Protection**
          - File locking prevents race conditions
          - 60-second timeout with deadlock protection
          - Safe parallel job execution
          
          ### 🎨 **Enhanced Logging**
          - Beautiful categorized output with emojis
          - Specialized methods: `cache()`, `checksum()`, `archive()`, `lock()`
          - Better error reporting and debugging
          
          ### ⚡ **Improved Reliability**
          - Atomic file operations prevent corruption
          - Temp-write-rename pattern for cache saves
          - Enhanced error handling and recovery
          
          ## 📦 Usage
          
          ```yaml
          - name: Cache dependencies
            uses: ozankasikci/github-actions-local-cache@${{ steps.version.outputs.VERSION }}
            with:
              path: |
                node_modules
                ~/.npm
              key: \${{ runner.os }}-deps-\${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                \${{ runner.os }}-deps-
          ```
          
          ## 🔗 Built Files
          
          Pre-built files are available on the [`release/${{ steps.version.outputs.VERSION }}`](https://github.com/${{ github.repository }}/tree/release/${{ steps.version.outputs.VERSION }}) branch.
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v1.4.2...${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}